version: "3.3"

services:
  sql-db:
    build:
      context: ./infrastructure/sql-db
    environment:
      MYSQL_ROOT_PASSWORD: codingchallenge
      MYSQL_DATABASE: codingchallenge
      MYSQL_USER: codingchallenge
      MYSQL_PASSWORD: codingchallenge
    ports:
      - "8322:3306"
    networks:
      - backend-php
  php-fpm:
    depends_on:
      - sql-db
      - nginx_backend
    build: ./infrastructure/php
    restart: always
    environment:
      MYSQL_DB_HOST: sql-db
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USER: codingchallenge
      MYSQL_DB_PASSWORD: codingchallenge
      MYSQL_DATABASE: codingchallenge
      DATABASE_URL: mysql://codingchallenge:codingchallenge@sql-db:3306/codingchallenge
    networks:
      - backend-php
    volumes:
      - sock:/sock
      - ./backend:/var/www
    links:
      - sql-db
  nginx_backend:
    build:
      context: ./infrastructure/nginx
    ports:
      - "8321:80"
    volumes:
      - ./backend:/var/www:delegated
      - sock:/sock
    networks:
      - backend-php
    restart: always
volumes:
  sock:

networks:
  backend-php:
